export const config = {
  app_name: "app_title_name",
  version: "1.0.0",
  web_config: {
    auth_local_storage: "auth-ce2b66af-2e75-4cad-b043-429b4ce77d99",
    web_local_storage: "web-ce2b66af-2e75-4cad-b043-429b4ce77d99",
    logo_login: `${process.env.PUBLIC_URL + "/logo_login.png"}`,
    logo_layout: `${process.env.PUBLIC_URL + "/logo_layout.png"}`,
    background_login: `url(${process.env.PUBLIC_URL + "/bk_login.jpg"})`,
    icon_url: "https://material.io/resources/icons/?style=baseline",
    core_base_url: "https://localhost:5001/api/v1/",
  },
  owner: {
    code: "-",
    name_thai: "-",
    name_eng: "-",
    address: "-",
    website: "-",
    email: "-",
    tel: "-",
    mobile_phone: "-",
    contact: "-",
    country: "-",
  },
  register: {
    register_id: "-",
    system_id: "-",
    name_thai: "-",
    name_eng: "-",
    address: "-",
    website: "-",
    email: "-",
    tel: "-",
    fax: "-",
    contract: "-",
    country: "-",
    register_date: null,
    activate_date: null,
    expire_date: null,
  },
  func: [
    {
      seq: 1,
      key: "main_about",
      func_name: "About",
      icon: "new_releases",
      path: "",
    },
  ],
};
